version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=devlopment
      - DATABASE_USER=root
      - MONGO_PASSWORD=example
    command: yarn dev
